# Generated by Django 4.0 on 2023-11-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_user_is_active_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sort_code',
            field=models.CharField(default=1, max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
