# Generated by Django 4.0 on 2023-11-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_account_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
