# Generated by Django 4.0 on 2023-11-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_account_account_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sort_code',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('savings', 'savings Account'), ('current', 'current Account')], max_length=10),
        ),
    ]
