# Generated by Django 4.0 on 2023-11-25 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_remove_account_iban_remove_account_sort_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransactionPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_pin', models.CharField(blank=True, max_length=4, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.user')),
            ],
        ),
    ]
