# Generated by Django 4.0 on 2023-11-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_usertransactionpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
